spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:schedule/schedule
    username: admin
    password: passw0rd
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
server:
  contextPath: /schedule
